name: green-ai
channels:
  - intel
  - defaults
dependencies:
  - ipython=8.9.0
  - openpyxl=3.0.10
  - pandas=1.5.1
  - pip=22.2.2
  - python=3.10.8
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scikit-learn-intelex=2023.0.1
  - setuptools=63.4.1
  - tqdm=4.64.0